server:
  port: 9000 #default : 8080

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://linirini-database.cxzcfcfn0rof.ap-northeast-2.rds.amazonaws.com/daangn_market?autoReconnect=true # 변경해주세요
    username: admin
    password: 2ghkddud!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전